---
meta:
  default:
    azs: [z1]

params:
  load-balancers: (( param "Please specify the full load balancer configuration" ))

instance_groups:
  - name:      lb
    instances: (( grab params.instances || 2 ))
    azs:       (( grab params.availability_zones || meta.default.azs ))
    stemcell:  default
    vm_resources:
      cpu: (( grab params.cpu || 2 ))
      ram: (( grab params.ram || 2048 ))
      ephemeral_disk_size: (( grab params.disk || 16384 ))
    networks:
      - name: (( grab params.network || "default" ))

    jobs:
      - name: haproxy
        release: load-balancer
        properties:
          load-balancers: (( grab params.load-balancers ))

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
- name:    load-balancer
  version: 0.1.0
  url:     https://github.com/genesis-community/load-balancer-boshrelease/releases/download/v0.1.0/load-balancer-0.1.0.tgz
  sha1:    9631ddbac1ef3431612a2d11220ab0bc6f0ae813
